apiVersion: config.k8ssandra.io/v1beta2
kind: ImageConfig
metadata:
  name: image-config
images:
  system-logger:
    registry: "ghcr.io"
    repository: "k8ssandra"
    name: "system-logger"
    tag: "latest"
  config-builder:
    repository: "datastax"
    name: "cass-config-builder"
    tag: "1.0-ubi"
  k8ssandra-client:
    repository: "k8ssandra"
    name: "k8ssandra-client"
    tag: "v0.8.3"
    # pullSecret: "k8ssandra-client-pull-secret" # Use of pullSecret removes the default pullSecrets for this image
    # pullPolicy: Always
# -- defaults are used when other no override is present for the configured image or image type. All these values can be overridden under any image or image type.
defaults:
  registry: "docker.io"
  pullPolicy: IfNotPresent
  # -- pullSecrets allow configuring the secret to use for pulling images from private registries.
  # pullSecrets:
  #   - my-secret-pull-registry
# -- overrides will apply to all images discarding the settings in defaults or what individual images might have.
# overrides:
# -- registry to pull from
# registry: "private-registry.local"
# -- repository to use discarding all the other settings. If set to empty, repository part will be removed from the image path.
# repository: "enterprise"
# -- pullPolicy override the pullPolicy of images
# pullPolicy: Never
# -- pullSecrets removes all the other pullSecrets when used. Setting as empty array will remove pullSecrets from use.
# pullSecrets:
#   - "my-secret-pull-registry"
# -- types are used as building blocks when serverVersion + serverType in the CassandraDatacenter is used
types:
  cassandra:
    registry: "ghcr.io"
    repository: "k8ssandra"
    name: "cass-management-api"
    suffix: "-ubi"
  dse:
    repository: "datastax"
    name: "dse-mgmtapi-6_8"
    suffix: "-ubi"
  # hcd:
  #   repository: "datastax"
  #   name: "hcd"
  #   suffix: "-ubi"
  #   pullSecret: "hcd-pull-secret" # Use of pullSecret removes the default pullSecrets for this image
  #   pullPolicy: IfNotPresent
